### ISSUE TITLE
Move from NEP-21 standard of the token to NEP-141

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-token-connector#21]

**Comment by mfornet** [comment]
Vanilla implementation of the standard can be found here: https://github.com/near/near-sdk-rs/pull/289

**Comment by ilblackdragon** [comment]
NEP-141 standards implementation is https://github.com/near/near-sdk-rs/pull/293 (still WIP based on some NEPs are still in progress) with example usage.

**Comment by sept-en** [comment]
Please, assign this to me.

**Comment by djsatok** [comment]
Closed by #39
