### ISSUE TITLE
Remove `burnResult` function from ERC20Locker

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-token-connector#25]
https://github.com/near/rainbow-token-connector/blob/master/erc20-connector/contracts/ERC20Locker.sol#L43-L47

**Comment by sept-en** [comment]
Assign me to this, please.

**Comment by mfornet** [comment]
What was the use case of the burn function?

It seems to me that it should have only work for a parallel connector transferring bridged NEP21 from ETH to native NEP21 in Near)

**Comment by sept-en** [comment]
> What was the use case of the burn function?
> 
> It seems to me that it should have only work for a parallel connector transferring bridged NEP21 from ETH to native NEP21 in Near)

It seems to be redundant and not used anywhere. Moreover, yesterday on the call @abacabadabacaba mentioned that this one could be a bug. As the `_parseProof` which is called inside consumes the proof as well. So any third party can burn produced proof in ERC20Locker (i.e. this specific proof become "used" and is not accepted anymore) and the appropriate amount of eth will be "locked" forever.

**Comment by djsatok** [comment]
@mfornet Illia mentioned that this is a leftover from the refactoring / debugging, no clear evidence why this appeared. The initial code [was not containing this](https://github.com/near/rainbow-token-connector/blame/0294289acdb5b7a42bfa6da8394d96ee0f7a7756/erc20-connector/contracts/ERC20Locker.sol).

This is a clear bug that should be fixed.
