### ISSUE TITLE
Set metadata of deployed tokens

### ISSUE THREAD

**Issue by mfornet** [near/rainbow-token-connector#46]
Set metadata of whitelisted deployed tokens: https://github.com/near/rainbow-bridge-frontend/issues/112

While metadata can't be set trustlessly (https://github.com/near/rainbow-token-connector/issues/47) let's leverage that bridge is deployed in PoA mode.

| Status | Bridge | ERC20 Address | Near Address |
|-|-|-|-|
| Pending | Mainnet | [DAI](https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f) | [nDAI](https://explorer.near.org/accounts/6b175474e89094c44da98b954eedeac495271d0f.factory.bridge.near)|
| Pending | Ropsten-Testnet |[TST](https://ropsten.etherscan.io/token/0x722dd3f80bac40c951b51bdd28dd19d435762180)|[nTST](https://explorer.testnet.near.org/accounts/722dd3f80bac40c951b51bdd28dd19d435762180.f.ropsten.testnet)|

**Comment by djsatok** [comment]
I've done this for mainnet deployment. I do have a script for this. What should we do with this script? I don't think this repo is suitable for it.
