### ISSUE TITLE
Infinite minting attack

### ISSUE THREAD

**Issue by Kouprin** [near/rainbow-token-connector#9]
@abacabadabacaba: More details about a vulnerability in rainbow-token-connector that I mentioned yesterday. This vulnerability allows creating nearly unlimited amount of a bridged NEAR token whose account ID length is 16 or less. The attack works as follows:

- An attacker creates their own ERC-20 token and sends a large amount of it over the bridge to NEAR.
- An attacker makes a transaction to withdraw the token back to Ethereum.
- Now, finish_withdraw method produces a SuccessValue which is a Borsh-serialized structure (amount: u128, token_address: [u8; 20], recipient: [u8; 20]). The attacker wants it to be interpreted as a result of finish_lock, which is (token_address: String, amount: u128, recipient: [u8; 20]). Here, amount and recipient from finish_withdraw are under full attacker's control, and token_address is under partial control (it is possible to "mine" a token address to make a few bytes have desired values). Also, the length of the entire structure is not checked, otherwise it would only have worked if token_address's length were exactly 16.
- Call BridgeTokenFactory.deposite() with the proof of the above SuccessValue to get lots of bridged tokens. Now the tokens can be sent back to NEAR, so the attacker can get all of the locked tokens there.

**Comment by mfornet** [comment]
Solved in #14
